/* INSERCION DE  ESPECIES */
BEGIN
    INSERTAR_ESPECIE('Perro', 'Canes');
    INSERTAR_ESPECIE('Gato', 'Felinos');
    INSERTAR_ESPECIE('Cobaya', 'Cavidos');
    INSERTAR_ESPECIE('Caballo', 'Equidos');
    INSERTAR_ESPECIE('Vaca/Toro', 'Bovino');
END;
/

/* INSERCION DE RAZAS */
BEGIN
    INSERTAR_RAZA('Angora', 5, 10);
    INSERTAR_RAZA('Persa', 5, 10);
    INSERTAR_RAZA('Mestizo', 5, 10);
    INSERTAR_RAZA('Himalayo', 5, 10);
    INSERTAR_RAZA('Pitbull', 4, 12);
    INSERTAR_RAZA('Mestizo', 4, 12);
    INSERTAR_RAZA('Pastor Aleman', 4, 12);
    INSERTAR_RAZA('Pastor Belga', 4, 12);
    INSERTAR_RAZA('Pug', 4, 12);
    INSERTAR_RAZA('Shiba', 4, 12);
END;


/* INSERCION DE MEDICOS */
BEGIN
    INSERTAR_MEDICO('Luis Felipe Zuniga', '98201105', '0612199625435', 'Los Alamos', 0);
    INSERTAR_MEDICO('Alejandra Perez', '88201105', '0612199665789', 'Res. Centro America', 1);
END;

/* INSERCION DE CITAS */

BEGIN
    INGRESAR_CITA('2022-02-03', 13, 'El paciente no quiere comer y vomita a cada rato', null, 4);
    INGRESAR_CITA('2022-01-12', 6, 'Paciente con dolores en el vientre', null, 8);
    INGRESAR_CITA('2022-03-17', 13, 'Vacuna contra la gripe', null, 6);
    INGRESAR_CITA('2022-01-05', 12, 'Paciente con Fiebre', null, 7);
    INGRESAR_CITA('2022-02-22', 10, 'Tratado de pata rota', null, 9); 
    INGRESAR_CITA('2022-02-27', 9, 'Sangrado de naris', null, 7);
    INGRESAR_CITA('2022-01-12', 11, 'Castrasion', null, 6);
    INGRESAR_CITA('2022-01-28', 7, 'Dolor en la pata', null, 6);
    INGRESAR_CITA('2022-03-20', 9, 'Caso de pulgas', null, 5);
    INGRESAR_CITA('2022-03-14', 8, 'Problemas de perdida de pelaje', null, 8);
    INGRESAR_CITA('2022-01-09', 6, 'Vacuna contra la rabia', null, 5);
    INGRESAR_CITA('2022-02-23', 12, 'Vitaminacion', null, 5);
    INGRESAR_CITA('2022-03-09', 8, 'Gripe aguda', null, 9);
    INGRESAR_CITA('2022-02-07', 6, 'Vitaminacion', null, 5);
END;

/*INSERSION EN CONTROL DE SISTEMA*/

BEGIN
    DELETE FROM CONTROL_SISTEMA;
    INSERT INTO CONTROL_SISTEMA VALUES(1, sysdate);
END;


/* PROBANDO CHUNCHES Y COSOS */

delete from CITAS;

select * from MEDICOS;

select * from CITAS;

select * from RAZAS;

select * from DUENOS; 

select * from PACIENTE;

select R.ID_RAZA, E.NOMBRE || ' ' || R.NOMBRE as Razas_animales from RAZAS R INNER JOIN ESPECIES E ON R.ID_ESPECIE = E.ID_ESPECIE;

BEGIN
    INSERTAR_PACIENTE('Pugberto', 9, 1, null, 'https://pbs.twimg.com/media/E7kDdoFVcAEuMjX?format=jpg', SYSDATE);
END;

select * from PACIENTE;

delete from PACIENTE;

/*Ejemplo de estraccion de fecha con hora*/
select P.ID_PACIENTE, P.NOMBRE, R.NOMBRE AS RAZA, E.NOMBRE AS ESPECIE, D.NOMBRE_COMPLETO AS DUENO, TO_CHAR(FECHA_PRIMERA_CITA, 'YYYY-MM-DD HH24:MI:SS') AS FECHA_PRIMERA_CITA from PACIENTE P INNER JOIN RAZAS R ON P.ID_RAZA = R.ID_RAZA INNER JOIN ESPECIES E ON R.ID_ESPECIE = E.ID_ESPECIE INNER JOIN DUENOS D ON P.ID_DUENO = D.ID_DUENO;

SELECT TO_CHAR(FECHA, 'MONTH',  'NLS_DATE_LANGUAGE = spanish') AS MES, FECHA from Citas ORDER BY FECHA ASC; 

/*
ROW_NUMBER() OVER (PARTITION BY TO_CHAR(C.FECHA, 'MONTH', 'NLS_DATE_LANGUAGE = spanish') ORDER BY C.FECHA) AS NUMERO,
LISTAGG(TD.TELEFONO, ',') WITHIN GROUP (ORDER BY TD.TELEFONO) AS TELEFONOS, 
*/


/* QUERY PARA EL REPORTE */
SELECT 
    ROW_NUMBER() OVER (PARTITION BY TO_CHAR(C.FECHA, 'MONTH', 'NLS_DATE_LANGUAGE = spanish') ORDER BY C.FECHA) AS NUMERO,
    TO_CHAR(C.FECHA, 'MONTH', 'NLS_DATE_LANGUAGE = spanish') AS MES, 
    TO_CHAR(C.FECHA, 'DD/MM/YYYY') AS FECHA_ASISTENCIA, 
    D.NOMBRE_COMPLETO AS NOMBRE_DUENO,
    LISTAGG(TD.TELEFONO, ',') WITHIN GROUP (ORDER BY TD.TELEFONO) AS TELEFONOS,
    P.NOMBRE AS NOMBRE_PACIENTE, 
    E.NOMBRE AS ESPECIE, 
    TO_CHAR(C.FECHA_PROGRAMACION, 'DD/MM/YYYY') AS FECHA_PROGRAMACION, 
    M.NOMBRE_COMPLETO AS MEDICO 
    from Citas C INNER JOIN PACIENTE P ON C.ID_PACIENTE = P.ID_PACIENTE 
    INNER JOIN RAZAS R ON R.ID_RAZA = P.ID_RAZA 
    INNER JOIN ESPECIES E ON R.ID_ESPECIE = E.ID_ESPECIE 
    INNER JOIN MEDICOS M ON C.ID_MEDICO = M.ID_MEDICO 
    INNER JOIN DUENOS D ON P.ID_DUENO = D.ID_DUENO
    LEFT JOIN TELEFONOS_DUENO TD ON D.ID_DUENO = TD.ID_DUENO
    GROUP BY C.ID_CITA, C.FECHA, D.NOMBRE_COMPLETO, P.NOMBRE, E.NOMBRE, C.FECHA_PROGRAMACION, M.NOMBRE_COMPLETO;



/* MAS QUERYES DE PRUEBA */
SELECT D.ID_DUENO, D.NOMBRE_COMPLETO AS NOMBRE, LISTAGG(TD.TELEFONO, ',') WITHIN GROUP (ORDER BY TD.TELEFONO) TELEFONOS FROM DUENOS D LEFT JOIN TELEFONOS_DUENO TD ON D.ID_DUENO = TD.ID_DUENO GROUP BY D.ID_DUENO, D.NOMBRE_COMPLETO;

SELECT D.ID_DUENO, D.NOMBRE_COMPLETO, TD.TELEFONO FROM DUENOS D LEFT JOIN TELEFONOS_DUENO TD ON D.ID_DUENO = TD.ID_DUENO;